### ISSUE TITLE
Can I add a lineComment in language-configuration.json ？

### ISSUE THREAD

**Issue by willclark314** [acaduser/otools#2]
Hi, I love this package, and it brings me a lot of help!
But a find a slight inconvenient, when I habitually hit 'Ctrl + /' to add a line comment but it doesn't work.
So I searched for the problem, and found that: if I add some code below
--------code--------
"comments": {
        "lineComment": ";",
        // I don't know how to set blockComment either
        // "blockComment": [ "" ]
    }
--------code--------
in language-configuration.json. It works!

**Comment by acaduser** [comment]
Thank you. I knew it was normal. I added it.
有難うございます。仰る通りあるのが普通と知りました。追加させていただきました。
